# Generated by Django 5.2.4 on 2025-07-17 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeboundary",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                help_text="Ranh giới địa lý của quận/huyện (Geographic boundary polygon)",
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentzone",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                help_text="Ranh giới vùng tuyển sinh (Enrollment zone boundary polygon)",
                srid=4326,
            ),
        ),
    ]
